// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvfnwewkruxbpcdbocpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2Zm53ZXdrcnV4YnBjZGJvY3BlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MTM2MDgsImV4cCI6MjA1OTQ4OTYwOH0.2s-5tDlmB3fh_D4POXcU6eRehAt6F1SJ9nHc638U37E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);